### PR TITLE
Extended format

### PR DESCRIPTION
**Pull request by alexef**
Add support for a JSON format that support all of "keys", "newImage" and "oldImage" if they are defined, plus the eventName and other metadata fields.

Fixes typos and incompatibility between NEW_IMAGE and REMOVE events.

### CODE REVIEW

**Comment by alexef** [comment]
I thought these changes may be useful for people using this plugin. Will try to get the update on rubygems by other means.

**Comment by marcosnils** [comment]
hey @alexef haven't had time to review this. Can you give a briefly description what you wanted to achieve with this?. So I can better understand without following the code.

**Comment by alexef** [comment]
Hi @marcosnils !

Currently, there is no way to get both new and old images in JSON format. This PR introduces an "extended" format that will convert from Dynamodb internal format into plain JSON. This is useful for indexing both images in Elasticsearch, without going through extra filters.

Additionally, it fixes a typo and a wrong assumption that an image is always available (wrong if the event type is REMOVE).

I saw that you are the owner of the gem https://rubygems.org/gems/logstash-input-dynamodb/versions/2.0.5-java that's why I made the PR here. The upstream repo @awslabs looks dead.

**Comment by marcosnils** [comment]
k. that makes sense. I guess the missing part would be to add tests and it's good to merge.

**Pull request closed without merging**
